spring.application.name=backend-impressoes

# ===============================
# CONFIGURAÇÃO DO POSTGRESQL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/sistema_impressoes
spring.datasource.username=postgres
spring.datasource.password=527463
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# CONFIGURAÇÃO DO JPA / HIBERNATE
# ===============================
# Mostra no terminal os comandos SQL que o Java está fazendo
spring.jpa.show-sql=true

# Formata o SQL no terminal para ficar legível
spring.jpa.properties.hibernate.format_sql=true

# Atualiza as tabelas automaticamente baseado no seu código Java
spring.jpa.hibernate.ddl-auto=update

# Configurações de E-mail (Gmail Real do Kayque)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
# spring.mail.username=${SMTP_USER}
# spring.mail.password=${SMTP_PASS}

spring.mail.username=kayquephoto@gmail.com
spring.mail.password=ssbucyhbkdbbfzwp

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Para evitar erro de CORS com o React (Vite)
spring.mvc.cors.allowed-origins=http://localhost:5173

